from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from hubit_app.views import (
    lista_centros,
    registro_usuario,
    login_usuario,
    perfil_usuario,
    comprar_bono,
    mi_bono,
    reservar_clase,
    cancelar_reserva,
    lista_bonos,
    api_lista_actividades,
    api_actividad_detalle,
    cancelar_reserva_espacio,
    panel_centro_view,
    panel_actividad_view,
    panel_calendario_view,
    panel_espacios_view,
    panel_admin_view,
    admin_actividades_view,
    admin_crear_actividad,
    admin_horarios_actividad,
    admin_crear_horario,
    admin_eliminar_actividad,
    admin_eliminar_horario,
    admin_profesores,
    admin_crear_profesor,
    admin_eliminar_profesor, 
    admin_espacios_actividad,
    admin_crear_espacio,
    admin_eliminar_espacio,
    admin_horarios_centro,
    admin_crear_horario_centro,
    admin_eliminar_horario_centro,
    admin_bonos,
    admin_crear_bono,
    admin_eliminar_bono,
    logout_usuario,
    chatbot,
)

urlpatterns = [
    path('admin/', admin.site.urls),

    # API
    path('api/centros/', lista_centros),
    path('api/actividades/', api_lista_actividades),
    path('api/registro/', registro_usuario),
    path('api/login/', login_usuario),
    path('api/perfil/', perfil_usuario),
    path('api/comprar-bono/', comprar_bono),
    path('api/mi-bono/', mi_bono),
    path('api/reservar/', reservar_clase),
    path('api/cancelar/', cancelar_reserva),
    path('api/bonos/', lista_bonos),
    path('api/actividad/<int:id>/', api_actividad_detalle),
    path("cancelar-reserva/<int:reserva_id>/", cancelar_reserva, name="cancelar_reserva"),
    path("cancelar-reserva-espacio/<int:reserva_id>/", cancelar_reserva_espacio,  name="cancelar_reserva_espacio"),
    path("panel-profesor/", panel_centro_view, name="panel_profesor"),
    path("panel-profesor/actividad/<int:actividad_id>/", panel_actividad_view, name="panel_actividad"),
    path("panel-profesor/calendario/", panel_calendario_view, name="panel_calendario"),
    path("panel-profesor/espacios/", panel_espacios_view, name="panel_espacios"),
    path("logout/", logout_usuario, name="logout"),
    path("panel-admin/", panel_admin_view, name="panel_admin"),
    path("panel-admin/actividades/", admin_actividades_view, name="admin_actividades"),
    path("panel-admin/crear-actividad/", admin_crear_actividad, name="admin_crear_actividad"),
    path("panel-admin/actividad/<int:actividad_id>/horarios/",admin_horarios_actividad, name="admin_horarios_actividad"),
    path("panel-admin/crear-horario/",admin_crear_horario,name="admin_crear_horario"),
    path("panel-admin/eliminar-actividad/<int:actividad_id>/",admin_eliminar_actividad,name="admin_eliminar_actividad"),
    path("panel-admin/eliminar-horario/<int:horario_id>/",admin_eliminar_horario,name="admin_eliminar_horario"),
    path("panel-admin/profesores/",admin_profesores,name="admin_profesores"),
    path("panel-admin/crear-profesor/",admin_crear_profesor, name="admin_crear_profesor"),
    path("panel-admin/eliminar-profesor/<int:profesor_id>/",admin_eliminar_profesor,name="admin_eliminar_profesor"),
    path("panel-admin/actividad/<int:actividad_id>/espacios/",admin_espacios_actividad,name="admin_espacios_actividad"),
    path("panel-admin/crear-espacio/",admin_crear_espacio,name="admin_crear_espacio"),
    path("panel-admin/eliminar-espacio/<int:espacio_id>/",admin_eliminar_espacio,name="admin_eliminar_espacio"),
    path("panel-admin/horarios-centro/", admin_horarios_centro, name="admin_horarios_centro"),
    path("panel-admin/crear-horario-centro/", admin_crear_horario_centro, name="admin_crear_horario_centro"),
    path("panel-admin/eliminar-horario-centro/<int:horario_id>/", admin_eliminar_horario_centro, name="admin_eliminar_horario_centro"),
    path("panel-admin/bonos/", admin_bonos, name="admin_bonos"),
    path("panel-admin/crear-bono/", admin_crear_bono, name="admin_crear_bono"),
    path("panel-admin/eliminar-bono/<int:bono_id>/", admin_eliminar_bono),
    path("chatbot/", chatbot),

    # FRONTEND
    path('', include('hubit_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)